# Generated by Django 5.2.4 on 2025-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_requestable',
            field=models.BooleanField(default=False, help_text='Allow users to request customization of this project'),
        ),
    ]
