# Generated by Django 5.2.4 on 2025-08-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Embedded video URL (YouTube, Vimeo, etc.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_video',
            field=models.URLField(blank=True, default='', help_text='Cloudinary video URL or external video link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='video_thumbnail',
            field=models.URLField(blank=True, default='', help_text='Cloudinary thumbnail URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, help_text='Cloudinary image URL'),
        ),
    ]
