# Generated by Django 5.2.4 on 2025-08-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_video_url_alter_product_product_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
