# Generated by Django 5.2.4 on 2025-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('business', 'Business'), ('fintech', 'Fintech'), ('technology', 'Technology'), ('tutorial', 'Tutorial'), ('case_study', 'Case Study'), ('industry_news', 'Industry News'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, help_text='Featured image URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(default='5 min read', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(default=list, help_text='List of tags for the post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Short description for preview', max_length=500),
        ),
    ]
