# Generated by Django 5.2.4 on 2025-08-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment_blogdownload_blogimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='Embedded video URL (YouTube, Vimeo, etc.)'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Cloudinary image URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, help_text='Featured image Cloudinary URL'),
        ),
    ]
