# Generated by Django 5.2.4 on 2025-08-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Featured image URL (external)'),
            preserve_default=False,
        ),
    ]
