import {
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  chromecast,
  disc02,
  discord,
  discordBlack,
  facebook,
  figma,
  file02,
  framer,
  homeSmile,
  instagram,
  notification2,
  notification3,
  notification4,
  notion,
  photoshop,
  plusSquare,
  protopie,
  raindrop,
  recording01,
  recording03,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  searchMd,
  slack,
  sliders04,
  telegram,
  twitter,
  yourlogo,
} from "../assets";

export const navigation = [
  {
    id: "0",
    title: "Home",
    url: "/",
  },
  {
    id: "1",
    title: "About",
    url: "/about",
  },
  {
    id: "2",
    title: "E-Learning",
    url: "/thinkforge",
  },
  {
    id: "3",
    title: "Projects",
    url: "/viorx",
  },
  {
    id: "4",
    title: "Shop",
    url: "/viormart",
  },
  {
    id: "5",
    title: "Scholar",
    url: "/scholar",
  },
  {
    id: "6",
    title: "Contact",
    url: "/contact",
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [yourlogo, yourlogo, yourlogo, yourlogo, yourlogo];

export const pritechviorServices = [
  "Final year & academic project development",
  "Enterprise system architecture & deployment", 
  "Custom software development (web/mobile)",
  "Documentation & technical mentorship",
  "Mobile-first PWA development",
];

export const brainwaveServicesIcons = [
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
];

export const roadmap = [
  {
    id: "0",
    title: "E-Learning Platform Launch",
    text: "Complete online education platform with instructor-led courses, certification programs, and global access through mobile payments.",
    date: "Q3 2025",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: "1",
    title: "Advanced POS & E-Commerce",
    text: "Launch comprehensive retail solution with offline-first POS system, inventory sync, and AzamPay integration for seamless payments.",
    date: "Q4 2025",
    status: "progress",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Software Archive & Hosting",
    text: "Deploy centralized digital resource hub with downloadable enterprise software and full cPanel hosting services.",
    date: "Q1 2026",
    status: "progress",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "AI Integration & Analytics",
    text: "Integrate advanced AI capabilities for business intelligence, automated reporting, and predictive analytics across all platforms.",
    date: "Q2 2026",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "With powerful internal collaboration tools, role-based access control, and real-time productivity features, it's the perfect solution for teams looking to work smarter and more efficiently.";

export const collabContent = [
  {
    id: "0",
    title: "Real-time Team Messaging",
    text: collabText,
  },
  {
    id: "1", 
    title: "Role-based Access Control",
  },
  {
    id: "2",
    title: "Financial & Treasury Management",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "Figma",
    icon: figma,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "Notion",
    icon: notion,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "Discord",
    icon: discord,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "Slack",
    icon: slack,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "Photoshop",
    icon: photoshop,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "Protopie",
    icon: protopie,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Framer",
    icon: framer,
    width: 26,
    height: 34,
  },
  {
    id: "7",
    title: "Raindrop",
    icon: raindrop,
    width: 38,
    height: 32,
  },
];

export const projects = [
  {
    id: "0",
    title: "Student Management System",
    description: "Complete academic project with modern UI",
    category: "Academic Project",
    technologies: [
      "React.js with responsive design and modern UI",
      "Node.js backend with RESTful APIs",
      "MySQL database with optimized queries",
      "User authentication and role management",
      "Real-time notifications and updates",
      "Complete documentation and deployment guide",
    ],
    image: "project1.jpg",
    status: "Completed",
  },
  {
    id: "1",
    title: "E-Commerce Platform",
    description: "Full-featured online store with POS integration",
    category: "Business Solution",
    technologies: [
      "Next.js e-commerce platform with admin panel",
      "Integrated POS system for offline sales",
      "AzamPay payment gateway integration",
      "Inventory management and tracking",
      "Customer analytics and reporting",
      "Mobile-responsive PWA design",
    ],
    image: "project2.jpg",
    status: "In Development",
  },
  {
    id: "2",
    title: "Enterprise ERP System",
    description: "Comprehensive business management solution",
    category: "Enterprise Solution",
    technologies: [
      "Microservices architecture with Docker",
      "Advanced role-based access control",
      "Financial management and treasury modules",
      "Real-time collaboration and messaging",
      "Custom reporting and analytics dashboards",
      "Cloud deployment with cPanel hosting",
    ],
    image: "project3.jpg",
    status: "Planning",
  },
];

// Blog Posts Data
export const blogPosts = [
  {
    id: "0",
    title: "Building Scalable Web Applications with React and Node.js",
    excerpt: "Learn how to create modern, scalable web applications using the latest technologies and best practices.",
    author: "PritechVior Team",
    date: "2025-07-30",
    category: "Web Development",
    readTime: "8 min read",
    featured: true,
    tags: ["React", "Node.js", "JavaScript", "Tutorial"],
  },
  {
    id: "1",
    title: "Digital Transformation for Tanzanian SMEs",
    excerpt: "A comprehensive guide to digital transformation strategies specifically tailored for small and medium enterprises in Tanzania.",
    author: "PritechVior Team",
    date: "2025-07-28",
    category: "Business",
    readTime: "12 min read",
    featured: false,
    tags: ["Digital Transformation", "SME", "Tanzania", "Strategy"],
  },
  {
    id: "2",
    title: "Integrating AzamPay for Seamless Mobile Payments",
    excerpt: "Step-by-step guide to implementing AzamPay payment gateway in your web and mobile applications.",
    author: "PritechVior Team",
    date: "2025-07-25",
    category: "Fintech",
    readTime: "10 min read",
    featured: true,
    tags: ["AzamPay", "Payment Gateway", "Mobile Money", "Integration"],
  },
];

// Software Archive Data
export const archiveItems = [
  {
    id: "0",
    title: "PritechVior Office Suite",
    description: "Complete office productivity suite with word processor, spreadsheet, and presentation tools",
    version: "2024.1",
    size: "245 MB",
    category: "Productivity",
    downloadCount: 1250,
    rating: 4.8,
    license: "Freemium",
    platforms: ["Windows", "macOS", "Linux"],
    featured: true,
  },
  {
    id: "1",
    title: "Student Project Manager",
    description: "Project management tool specifically designed for academic and final year projects",
    version: "1.5.2",
    size: "89 MB",
    category: "Education",
    downloadCount: 890,
    rating: 4.6,
    license: "Free",
    platforms: ["Windows", "macOS"],
    featured: false,
  },
  {
    id: "2",
    title: "SME Financial Tracker",
    description: "Simple yet powerful financial management software for small and medium enterprises",
    version: "3.0.1",
    size: "156 MB",
    category: "Finance",
    downloadCount: 567,
    rating: 4.7,
    license: "Premium",
    platforms: ["Windows", "Web"],
    featured: true,
  },
];

// ThinkForge Courses Data
export const courses = [
  {
    id: "0",
    title: "Full-Stack Web Development with MERN",
    description: "Complete course covering MongoDB, Express.js, React, and Node.js development",
    instructor: "PritechVior Academy",
    duration: "12 weeks",
    level: "Intermediate",
    price: "150,000 TZS",
    category: "Programming",
    enrolled: 245,
    rating: 4.9,
    featured: true,
    modules: 8,
    projects: 3,
  },
  {
    id: "1",
    title: "Digital Marketing for Tanzanian Businesses",
    description: "Learn effective digital marketing strategies tailored for the Tanzanian market",
    instructor: "PritechVior Academy",
    duration: "8 weeks",
    level: "Beginner",
    price: "85,000 TZS",
    category: "Marketing",
    enrolled: 189,
    rating: 4.7,
    featured: false,
    modules: 6,
    projects: 2,
  },
  {
    id: "2",
    title: "Mobile App Development with React Native",
    description: "Build cross-platform mobile applications for Android and iOS",
    instructor: "PritechVior Academy",
    duration: "10 weeks",
    level: "Intermediate",
    price: "200,000 TZS",
    category: "Mobile Development",
    enrolled: 156,
    rating: 4.8,
    featured: true,
    modules: 10,
    projects: 4,
  },
];

// ViorMart Products Data
export const products = [
  {
    id: "0",
    title: "MacBook Pro 14-inch M3",
    description: "Latest MacBook Pro with M3 chip, perfect for development and creative work",
    price: "4,500,000 TZS",
    originalPrice: "4,800,000 TZS",
    category: "Laptops",
    brand: "Apple",
    inStock: true,
    rating: 4.9,
    reviews: 128,
    featured: true,
    isAffiliate: true,
    affiliateSource: "Amazon",
  },
  {
    id: "1",
    title: "Custom Website Development",
    description: "Professional website development service for businesses and startups",
    price: "800,000 TZS",
    originalPrice: null,
    category: "Services",
    brand: "PritechVior",
    inStock: true,
    rating: 5.0,
    reviews: 45,
    featured: true,
    isAffiliate: false,
    affiliateSource: null,
  },
  {
    id: "2",
    title: "Logitech MX Master 3S Mouse",
    description: "Advanced wireless mouse for professionals and creatives",
    price: "180,000 TZS",
    originalPrice: "200,000 TZS",
    category: "Accessories",
    brand: "Logitech",
    inStock: true,
    rating: 4.8,
    reviews: 89,
    featured: false,
    isAffiliate: true,
    affiliateSource: "Amazon",
  },
];

export const benefits = [
  {
    id: "0",
    title: "Project Design & Implementation",
    text: "End-to-end project support for students, startups, and enterprises. Final year projects, enterprise systems, custom software development, and technical mentorship.",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
    icon: "Settings",
  },
  {
    id: "1",
    title: "IT Consulting & Innovation Solutions",
    text: "Strategic digital transformation support with IT system audits, architectural planning, and tailored solutions for startups, NGOs & schools.",
    backgroundUrl: "./src/assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
    icon: "Brain",
  },
  {
    id: "2",
    title: "E-Learning & Digital Training",
    text: "Full online education platform with instructor-led courses, certifications, progress tracking, and global access with mobile payments.",
    backgroundUrl: "./src/assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
    icon: "GraduationCap",
  },
  {
    id: "3",
    title: "E-Commerce & POS Solutions",
    text: "Smart retail tools with online store, offline-first POS system, inventory sync, and AzamPay integration for seamless payments.",
    backgroundUrl: "./src/assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
    icon: "ShoppingCart",
  },
  {
    id: "4",
    title: "Internal Collaboration & Management",
    text: "Powerful productivity tools with real-time messaging, role-based access, financial modules, and system-wide notifications.",
    backgroundUrl: "./src/assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
    icon: "MessageSquare",
  },
  {
    id: "5",
    title: "Software Archive & Hosting Services",
    text: "Centralized digital resource hub with downloadable software, cPanel hosting, mobile-first PWA websites, and app store interface.",
    backgroundUrl: "./src/assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    icon: "Database",
  },
];

// Vior X/Student Resources Data
export const scholarResources = [
  {
    id: "0",
    title: "Final Year Project Development",
    description: "Complete support for your final year project from ideation to deployment",
    category: "Project Support",
    duration: "3-6 months",
    price: "300,000 TZS",
    features: [
      "Project topic selection and research",
      "Complete system analysis and design",
      "Full stack development (Frontend + Backend)",
      "Database design and implementation",
      "Testing and quality assurance",
      "Documentation and presentation preparation",
      "Deployment and hosting setup",
      "Post-graduation technical support"
    ],
    technologies: ["React", "Node.js", "MySQL", "MongoDB"],
    difficulty: "Advanced",
    rating: 4.9,
    studentsHelped: 150,
    featured: true,
  },
  {
    id: "1",
    title: "Academic Research & Writing",
    description: "Professional assistance with research papers, dissertations, and academic writing",
    category: "Research Support",
    duration: "2-4 weeks",
    price: "150,000 TZS",
    features: [
      "Research topic development",
      "Literature review and analysis",
      "Data collection and analysis",
      "Academic writing and formatting",
      "Citation and referencing (APA, MLA, Harvard)",
      "Plagiarism checking and originality",
      "Peer review and feedback",
      "Presentation preparation"
    ],
    technologies: ["SPSS", "R", "LaTeX", "Mendeley"],
    difficulty: "Intermediate",
    rating: 4.8,
    studentsHelped: 89,
    featured: true,
  },
  {
    id: "2",
    title: "Programming Tutoring & Mentorship",
    description: "One-on-one programming lessons and career mentorship for students",
    category: "Learning Support",
    duration: "Flexible",
    price: "50,000 TZS/month",
    features: [
      "Personalized learning roadmap",
      "Weekly one-on-one sessions",
      "Hands-on coding practice",
      "Project-based learning approach",
      "Industry best practices training",
      "Career guidance and advice",
      "Interview preparation",
      "Job placement assistance"
    ],
    technologies: ["Python", "JavaScript", "Java", "C++"],
    difficulty: "Beginner to Advanced",
    rating: 4.9,
    studentsHelped: 234,
    featured: false,
  },
  {
    id: "3",
    title: "Student Project Templates",
    description: "Ready-to-use project templates for various academic levels and subjects",
    category: "Templates & Resources",
    duration: "Instant Access",
    price: "25,000 TZS",
    features: [
      "50+ project templates available",
      "Multiple programming languages",
      "Complete source code included",
      "Detailed documentation",
      "Setup and installation guides",
      "Customization tutorials",
      "Free updates for 1 year",
      "Community support access"
    ],
    technologies: ["Various", "Multi-platform"],
    difficulty: "Beginner to Intermediate",
    rating: 4.7,
    studentsHelped: 445,
    featured: false,
  },
];

// Student Success Stories
export const studentStories = [
  {
    id: "0",
    name: "Amina Hassan",
    university: "University of Dar es Salaam",
    course: "Computer Science",
    year: "2024",
    project: "E-Commerce Platform for Local SMEs",
    grade: "A",
    testimonial: "PritechVior helped me build an amazing final year project that impressed my supervisors. The mentorship was exceptional!",
    avatar: "student1.jpg",
    linkedIn: "#",
  },
  {
    id: "1",
    name: "John Mwalimu",
    university: "Sokoine University",
    course: "Information Systems",
    year: "2024",
    project: "Farm Management System",
    grade: "A+",
    testimonial: "The guidance I received was invaluable. My project went beyond requirements and I'm now working as a software developer.",
    avatar: "student2.jpg",
    linkedIn: "#",
  },
  {
    id: "2",
    name: "Grace Kimaro",
    university: "Mzumbe University",
    course: "Business Information Technology",
    year: "2023",
    project: "Student Information Management System",
    grade: "A",
    testimonial: "Professional support throughout my project. The team helped me understand complex concepts and deliver quality work.",
    avatar: "student3.jpg",
    linkedIn: "#",
  },
];

// Academic Resources
export const academicResources = [
  {
    id: "0",
    title: "Research Methodology Guide",
    type: "PDF Guide",
    size: "2.5 MB",
    pages: 45,
    downloads: 1250,
    category: "Research",
    description: "Comprehensive guide to academic research methodology",
    free: true,
  },
  {
    id: "1",
    title: "Project Proposal Templates",
    type: "Document Package",
    size: "5.2 MB",
    pages: 30,
    downloads: 890,
    category: "Templates",
    description: "Professional project proposal templates for various fields",
    free: true,
  },
  {
    id: "2",
    title: "Citation Style Guide",
    type: "Quick Reference",
    size: "1.8 MB",
    pages: 20,
    downloads: 2100,
    category: "Writing",
    description: "APA, MLA, and Harvard citation styles with examples",
    free: true,
  },
];

export const socials = [
  {
    id: "0",
    title: "Discord",
    iconUrl: discordBlack,
    url: "#",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: twitter,
    url: "#",
  },
  {
    id: "2",
    title: "Instagram",
    iconUrl: instagram,
    url: "#",
  },
  {
    id: "3",
    title: "Telegram",
    iconUrl: telegram,
    url: "#",
  },
  {
    id: "4",
    title: "Facebook",
    iconUrl: facebook,
    url: "#",
  },
];
