# Generated by Django 5.2.4 on 2025-08-02 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('project', 'Project'), ('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(upload_to='archives/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
