# Generated by Django 5.2.4 on 2025-08-15 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='download_url',
            field=models.URLField(blank=True, help_text='External download URL if not hosting file'),
        ),
        migrations.AddField(
            model_name='archive',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='file_size_display',
            field=models.CharField(blank=True, help_text='Human readable file size', max_length=20),
        ),
        migrations.AddField(
            model_name='archive',
            name='license',
            field=models.CharField(choices=[('free', 'Free'), ('licensed', 'Licensed'), ('free_pro', 'Free/Pro'), ('free_personal_business', 'Free Personal/Business'), ('trial', 'Trial')], default='free', max_length=30),
        ),
        migrations.AddField(
            model_name='archive',
            name='platforms',
            field=models.JSONField(default=list, help_text='List of supported platforms'),
        ),
        migrations.AddField(
            model_name='archive',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='archive',
            name='request_only',
            field=models.BooleanField(default=True, help_text='Require contact for download'),
        ),
        migrations.AddField(
            model_name='archive',
            name='requirements',
            field=models.TextField(blank=True, help_text='System requirements'),
        ),
        migrations.AddField(
            model_name='archive',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='archive',
            name='category',
            field=models.CharField(choices=[('productivity', 'Productivity'), ('design', 'Design'), ('development', 'Development'), ('browser', 'Browser'), ('utilities', 'Utilities'), ('media', 'Media'), ('security', 'Security'), ('communication', 'Communication'), ('remote_access', 'Remote Access'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='archives/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ArchiveDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='archive.archive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('archive', 'user')},
            },
        ),
    ]
