# Generated by Django 5.2.4 on 2025-08-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archive_download_url_archive_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='download_url',
        ),
        migrations.AddField(
            model_name='archive',
            name='download_instructions',
            field=models.TextField(blank=True, help_text='Special download instructions'),
        ),
        migrations.AddField(
            model_name='archive',
            name='external_url',
            field=models.URLField(blank=True, help_text='External download/source URL'),
        ),
        migrations.AddField(
            model_name='archive',
            name='github_repo',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='archive',
            name='mirror_links',
            field=models.JSONField(default=list, help_text='Alternative download mirrors'),
        ),
        migrations.AddField(
            model_name='archive',
            name='official_website',
            field=models.URLField(blank=True, help_text='Official website URL'),
        ),
        migrations.AddField(
            model_name='archive',
            name='source_type',
            field=models.CharField(choices=[('hosted', 'Hosted File'), ('external', 'External Download'), ('github', 'GitHub Release'), ('official', 'Official Website'), ('direct', 'Direct Link'), ('mirror', 'Mirror Site')], default='hosted', max_length=20),
        ),
        migrations.AlterField(
            model_name='archive',
            name='request_only',
            field=models.BooleanField(default=False, help_text='Require contact for download'),
        ),
    ]
