# Generated by Django 5.2.4 on 2025-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_remove_archive_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='download_url',
            field=models.URLField(blank=True, help_text='External download URL if not hosting file'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='download_instructions',
            field=models.TextField(blank=True, help_text='Instructions for downloading from external sources'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='external_url',
            field=models.URLField(blank=True, help_text='External source URL'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='mirror_links',
            field=models.JSONField(blank=True, default=list, help_text='List of mirror download links'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='request_only',
            field=models.BooleanField(default=True, help_text='Require contact for download'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('external', 'External Source'), ('github', 'GitHub Repository'), ('official', 'Official Website')], default='file', max_length=20),
        ),
    ]
