# Generated by Django 5.2.4 on 2025-08-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_additional_roles_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('parent', 'Parent'), ('trainer', 'Trainer'), ('client', 'Client'), ('designer', 'Designer'), ('writer', 'Writer'), ('technician', 'Technician'), ('admin', 'Admin'), ('treasury', 'Treasury'), ('ceo', 'CEO')], max_length=20, unique=True)),
                ('is_visible_on_registration', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display on registration page')),
                ('description', models.TextField(blank=True, help_text='Role description for users')),
                ('icon', models.CharField(blank=True, help_text='Icon name for frontend display', max_length=50)),
            ],
            options={
                'ordering': ['display_order', 'role_name'],
            },
        ),
        migrations.AddField(
            model_name='customrole',
            name='description',
            field=models.TextField(blank=True, help_text='Role description for users'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name for frontend display', max_length=50),
        ),
        migrations.AddField(
            model_name='customrole',
            name='is_visible_on_registration',
            field=models.BooleanField(default=True, help_text='Show this role on registration page'),
        ),
    ]
